channels:
- defaults
dependencies:
- _anaconda_depends
- python=3.11
- setuptools
- pip
- wheel
- anaconda-anon-usage
- anaconda-catalogs
- anaconda-client
- anaconda-project
- anaconda-navigator
- conda
- conda-build
- conda-content-trust
- conda-libmamba-solver
- conda-pack
- conda-package-handling
- conda-package-streaming
- conda-token
- conda-verify
- menuinst[version='>=1.0.0a0,<2.0.0']
- console_shortcut
- powershell_shortcut
- anaconda-toolbox
- sphinx-rtd-theme
- pip:
  - absl-py==2.1.0
  - astunparse==1.6.3
  - flatbuffers==24.3.25
  - gast==0.6.0
  - google-pasta==0.2.0
  - grpcio==1.65.4
  - keras==3.4.1
  - libclang==18.1.1
  - ml-dtypes==0.4.0
  - namex==0.0.8
  - opt-einsum==3.3.0
  - optree==0.12.1
  - protobuf==4.25.4
  - rlcard==1.2.0
  - tensorboard==2.17.0
  - tensorboard-data-server==0.7.2
  - tensorflow==2.17.0
  - tensorflow-intel==2.17.0
  - tensorflow-io-gcs-filesystem==0.31.0
  - termcolor==2.4.0
name: lqfn
