channels:
- defaults
dependencies:
- python=3.11
- scipy
- numpy
- matplotlib
- ipykernel
- jupyter
- conda
- pre-commit
- sphinx
- sphinx_rtd_theme
- pylint
- pytest
- sympy
- numba
- pip:
  - gvar==13.1.1
  - h5py==3.11.0
  - progressbar==2.5
  - qmsolve==2.0.0
  - sphinx-math-dollar==1.2.1
  - vegas==6.1.3
name: lqfn
